# Generated by Django 5.1.1 on 2024-11-15 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_debitcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.RegexValidator(message='Card number must contain exactly 16 digits.', regex='^\\d{16}$')]),
        ),
    ]
