# Generated by Django 5.1.1 on 2024-11-16 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_debitcard_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='card_number',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.RegexValidator(message='Card number must contain exactly 16 digits.', regex='^\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='debitcard',
            name='cvv',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='CVV must be exactly 3 digits.', regex='^\\d{3}$')]),
        ),
    ]
