# Generated by Django 5.1.1 on 2024-11-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_debitcard_card_number_alter_debitcard_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcard',
            name='used_for_payments',
            field=models.BooleanField(default=False),
        ),
    ]
