# Generated by Django 5.1.1 on 2024-12-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_artfluenceuser_has_bought_art_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='expiration_date',
            field=models.CharField(),
        ),
    ]
