# Generated by Django 5.1.1 on 2024-12-02 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_debitcard_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='expiration_date',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(message='Cardholder name must contain only letters and spaces.', regex='^(0[1-9]|1[0-2])/2\\d$')]),
        ),
    ]
