# Generated by Django 5.1.1 on 2024-11-18 13:35

import Artfluence.posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='art_pictures/', validators=[Artfluence.posts.validators.validate_file_size]),
        ),
    ]
